---
- hosts: all
  become: yes

  pre_tasks:
    - name: Create xml file for testing purpose
      copy:
        src: tests/test.xml
        dest: /tmp/test.xml
        owner: "{{ sphinx_user }}"
        group: "{{ sphinx_group }}"
        mode: 0644

  roles:
    - role: ansible-sphinxsearch
