---
- name: Update defaults option for sphinx
  template:
    src: sphinxsearch.default.j2
    dest: /etc/default/sphinxsearch
    owner: "{{ sphinx_user }}"
    group: "{{ sphinx_group }}"
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Create flat configuration file
  template:
    src: sphinx.conf.j2
    dest: '/etc/sphinxsearch/sphinx.conf'
    owner: "{{ sphinx_user }}"
    group: "{{ sphinx_group }}"
    mode: 0644
  notify:
    - restart sphinx

- name: Rotate all indexes
  command: /usr/bin/indexer --rotate --all
  ignore_errors: True
  when: sphinx_rotate_all