---
- name: Update defaults option for sphinx
  template:
    src: sphinxsearch.default.j2
    dest: /etc/default/sphinxsearch
    owner: "{{ sphinx_user }}"
    group: "{{ sphinx_group }}"
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Create flat configuration file
  template:
    src: sphinx.conf.j2
    dest: '/etc/sphinxsearch/sphinx.conf'
    owner: "{{ sphinx_user }}"
    group: "{{ sphinx_group }}"
    mode: 0644
  notify:
    - restart sphinx

- name: Check if we have indexes
  shell: ls /var/lib/sphinxsearch/data/*sph
  ignore_errors: True
  register: check_indexes

- name: Rotate all indexes
  command: /usr/bin/indexer --rotate --all
  ignore_errors: True
  changed_when: False
  when: (sphinx_rotate_all and check_indexes.rc != 0) or sphinx_force_rotate
